[terminal.shell]
program = "/usr/local/bin/fish"

[env]
TERM = "xterm-256color"

[general]
import = ["vague.toml"]

[window]
# opacity = 1
# blur = true
decorations = "none"
option_as_alt = "Both"
dynamic_padding = true

[window.padding]
x = 0
y = 0

[font]
size = 16

[font.normal]
family = "Hack Nerd Font Mono"

[keyboard]
bindings = [
  { key = "Enter", mods = "Command", action="ToggleFullscreen"},
  { key = "c", mods = "Command", action="Copy"},
  { key = "v", mods = "Command", action="Paste"},
]
