set -g default-terminal "tmux-256color"
set -a terminal-features "tmux-256color:RGB"

set -g prefix C-SPACE
set -g base-index 1
set -g renumber-windows on
set -g history-limit 50000
set -g mode-keys vi
set -g status-position bottom
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g window-status-current-style "fg=red bold"
set -g pane-border-style fg=brightblack
set -g pane-active-border-style fg=red
set -g status-right ""
set -g status-left " #S"
set -g mouse on
set -g extended-keys on
set -g extended-keys-format csi-u

set -s escape-time 0

unbind '%'
unbind '"'
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"


bind -r m resize-pane -Z
bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5

bind -r C-l send-keys "C-l"
bind -r C-a send-keys "C-a"


# bind-key -T copy-mode-vi "v" send -X begin-selection # start selecting text with "v"
# bind-key -T copy-mode-vi "y" send -X copy-selection # copy text with "y"

# unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode when dragging with mouse

bind r source-file "$HOME/.config/tmux/tmux.conf"
set-environment -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.config/tmux/plugins"

set -g @plugin "tmux-plugins/tpm"
set -g @plugin "christoomey/vim-tmux-navigator"

run "$HOME/.config/tmux/plugins/tpm/tpm"
