return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "asm",
      "json",
      "javascript",
      "typescript",
      "yaml",
      "html",
      "markdown",
      "markdown_inline",
      "bash",
      "lua",
      "vim",
      "dockerfile",
      "gitignore",
      "vimdoc",
      "c",
      "diff",
      "disassembly",
      "go",
      "http",
      "java",
      "python",
      "rust",
      "ruby",
      "xml",
    },
  },
}
