import = [
    "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[shell]
program = "/usr/local/bin/fish"

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

# opacity = 1
# blur = true

option_as_alt = "Both"

[font]
normal.family = "Hack Nerd Font Mono"

size = 16

[keyboard]
bindings = [
  { key = "Enter", mods = "Command", action="ToggleFullscreen"},
  { key = "c", mods = "Command", action="Copy"},
  { key = "t", mods = "Command", action="CreateNewTab"},
  { key = "ArrowLeft", mods = "Command", action="SelectPreviousTab"},
  { key = "ArrowRight", mods = "Command", action="SelectNextTab"},
]
